# Colors (Catppuccin Mocha)
$background = 0xFF1E1E2E
$base = 0xFF181825
$text = 0xFFCDD6F4
$alternate_base = 0xFF313244
$bright_text = 0xFFF5E0DC
$accent = 0xFFCBA6F7
$accent_secondary = 0xFF89B4FA

# Typography
$font_family = ComicCodeLigatures Nerd Font Mono
$font_family_monospace = ComicCodeLigatures Nerd Font Mono

# Font Sizes (Minimum 20px)
$font_size = 20
$small_font_size = 20
$h3_size = 22
$h2_size = 26
$h1_size = 32

# Application of settings
background = $background
base = $base
text = $text
alternate_base = $alternate_base
bright_text = $bright_text
accent = $accent
accent_secondary = $accent_secondary

font_family = $font_family
font_family_monospace = $font_family_monospace

font_size = $font_size
small_font_size = $small_font_size
h3_size = $h3_size
h2_size = $h2_size
h1_size = $h1_size

# Visuals
rounding_large = 6
rounding_small = 5
