splash=false

wallpaper {
    monitor = DP-2
    path = ~/.config/hypr/wallpaper.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = ~/.config/hypr/wallpaper.jpg
    fit_mode = cover
}
