splash=false
preload=~/.config/hypr/black.png
preload=~/.config/hypr/nier.jpg

wallpaper {
    monitor = DP-2
    path = ~/.config/hypr/nier.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = ~/.config/hypr/nier.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-2
    path = ~/.config/hypr/nier.jpg
    fit_mode = cover
}
