return {
  "milanglacier/minuet-ai.nvim",
  event = "InsertEnter",
  opts = {
    provider = "openai_compatible",
    request_timeout = 3,

    blink = {
      enable_auto_complete = false,
    },
    virtualtext = {
      auto_trigger_ft = { "*" },
      auto_trigger_ignore_ft = {
        "env",
        "dotenv",
        "help",
        "lazy",
        "TelescopePrompt",
        "terminal",
        "trouble",
        "qf",
        "fugitive",
        "fugitiveblame",
        "git",
        "gitcommit",
        "gitrebase",
        "DressingInput",
        "neo-tree",
        "noice",
        "notify",
        "alpha",
        "snacks_dashboard",
        "starter",
        "lspinfo",
        "checkhealth",
        "lspconfig",
        "neogit",
        "neogitlog",
        "DiffviewFiles",
        "DiffviewFileHistory",
        "toggleterm",
        "lazy.term",
      },
      keymap = {
        accept = "<C-l>",
        accept_line = false,
        accept_n_lines = false,
        prev = false,
        next = false,
        dismiss = "<C-]>",
      },
      show_on_completion_menu = false,
    },

    provider_options = {
      openai_compatible = {
        name = "Openrouter",
        end_point = "https://openrouter.ai/api/v1/chat/completions",
        model = "xiaomi/mimo-v2.5",
        optional = {
          max_tokens = 256,
          top_p = 0.9,
          provider = {
            order = {
              "DigitalOcean",
              "Hetzner",
              "Vultr",
              "OVHcloud",
              "Scaleway",
            },
            allow_fallbacks = true,
          },
        },
      },
    },
  },
}
