$menu = tofi-drun --drun-launch=true
# $menu = hyprlauncher
$terminal = ghostty || alacritty || kitty
$browser = brave
$discord = flatpak run com.discordapp.Discord
$mail = thunderbird
$calendar = thunderbird --calendar
$filemanager = nautilus
$screenshot = hyprshot -m region --clipboard-only
