$menu = tofi-drun --drun-launch=true
# $menu = hyprlauncher
$terminal = ghostty || alacritty || kitty
$browser = brave --disable-features=WaylandWpColorManagerV1
$whatsapp = brave --app="https://web.whatsapp.com"
$messages = brave --app="https://messages.google.com"
$discord = flatpak run com.discordapp.Discord
$signal = org.signal.Signal
$mail = thunderbird
$calendar = thunderbird --calendar
$filemanager = nautilus
$screenshot = hyprshot -m region --clipboard-only
$jellyfin = flatpak run org.jellyfin.JellyfinDesktop
