# hyprlang if HOST_CROSS_BATTLESTATION
windowrule {
  name = cb-pip
  float = on
  pin = on
  opaque = on
  no_dim = on
  monitor = $monitor2
  move = (monitor_w-1568) (monitor_h-914)
  size = 1568 882
  match:title = ^(Picture in picture)$
}

windowrule {
  name = cb-mpv
  float = on
  pin = on
  no_dim = on
  monitor = $monitor2
  move = (monitor_w-1568) (monitor_h-914)
  size = 1568 882
  match:initial_class = ^(mpv)$
}
# hyprlang endif

# hyprlang if HOST_CROSS_WORKSTATION
windowrule {
  name = cw-pip
  float = on
  pin = on
  no_initial_focus = on
  opacity = 1 override 1 override
  no_dim = on
  group = barred
  monitor = $monitor2
  move = 0 1245
  size = 1200 675
  match:title = ^(Picture in picture)$
}

windowrule {
  name = cw-mpv
  float = on
  pin = on
  no_initial_focus = on
  no_dim = on
  monitor = $monitor2
  move = 0 1245
  size = 1200 675
  match:initial_class = ^(mpv)$
}
# hyprlang endif

windowrule {
  name = jellifin-media-player
  no_dim = on
  opaque = on
  monitor = $monitor2
  move = 0 1245
  size = 1200 675
  match:initial_class = ^(com.github.iwalton3.jellyfin-media-player)$
}

windowrule {
  name = obs
  no_dim = on
  opacity = 1 override 1 override
  match:class = obs
}

windowrule {
  name = pinned
  border_size = 0
  no_initial_focus = on
  suppress_event = activeatefocus
  focus_on_activate = off
  match:pin = 1
}

windowrule {
  name = fullscreen
  border_size = 0
  opacity = 1 override 1 override
  no_dim = on
  idle_inhibit = fullscreen
  match:fullscreen = 1
}

windowrule {
  name = steam
  workspace = 2
  match:class = ^steam
}

windowrule {
  name = steam-game
  workspace = 2
  match:class = ^steam_app_\d+$
}

windowrule {
  name = gamescope
  workspace = 2
  match:class = ^gamescope
}

windowrule {
  name = pavuctonrol
  float = on
  size = 1000 900
  center = 1
  match:class = ^(org.pulseaudio.pavucontrol)$
}

windowrule {
  name = portal-stuff
  float = on
  size = 1000 900
  center = 1
  match:class = xdg-desktop-portal-gtk
}

windowrule {
  name = savefile
  float = on
  size = 1000 900
  center = 1
  match:title = ^(Save File)$
}

windowrule {
  name = openfile
  float = on
  size = 1000 900
  center = 1
  match:title = ^(Open File)$
}

windowrule {
  name = blueman
  float = on
  size = 1000 900
  center = 1

  match:class = ^(.blueman-manager-wrapped)$
}

windowrule {
  name = idle-inhibit
  idle_inhibit = fullscreen
  match:class = ^(*)$
}

windowrule {
  name = discord
  workspace = 7
  match:class = discord
}

windowrule {
  name = discord-canary
  workspace = 7
  match:class = discord-canary
}

windowrule {
  name = thunderbird
  workspace = 8
  match:class = thunderbird
}

